name: Publish to RubyGems

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Ruby Gem

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4" # Use a stable, recent Ruby version
          bundler-cache: true

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Build the gem
        run: gem build shield_ast.gemspec

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p ~/.gem
          echo ":rubygems_api_key: $GEM_HOST_API_KEY" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem push shield_ast-*.gem
